version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/buildwise-app
hooks:
  BeforeInstall:
  ApplicationStart:
    - location: scripts/after_install.sh
      timeout: 300
      runas: ec2-user
